name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.6.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@7c25cb0b5eadac32bfedbb3b60ca0bd4289791f1
    permissions:
      contents: read
      id-token: write
