name: Run TS tests
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test-ts:
    name: 'jsbt v0.7.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test.yml@78e04b481416536e0d4369a3c9f718be306491f8 # 0.7.0
